### PR TITLE
feat: add object creation benchmarks

### PR DESCRIPTION
**Pull request by anonrig**
Solves https://github.com/RafaelGSS/nodejs-bench-operations/issues/14

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Comment by RafaelGSS** [comment]
I have some ideas, but I'll implement them in another PR. Thanks!

**Comment by anonrig** [comment]
Result: Cached empty.prototype is 20x faster in node 14 and 10x faster in node 18

**Comment by RafaelGSS** [comment]
Actually, that's not a fair benchmark. Cached empty.prototype performs fewer CPU operations and doesn't need to create an object on every call or allocate memory space. Those micro-benchmarks are very tricky, it depends on several variables such as the warm-up of the V8, the execution order and so forth.

I think we could be slightly better if we use a _cached_ version on Object.create (`Object.create(cachedObject)`)

**Pull request merged**
