### PR TITLE
feat: benchmark stream web readable

### PR DESCRIPTION
**Pull request by RafaelGSS**
I have tried to create a fair comparisson between these implementations.

However, I'm not sure if the results are confidents. I really would like to get your thoughts here: @mcollina @jasnell

### CODE REVIEW

**Comment by RafaelGSS** [comment]
Results I got locally: 

```
streams.Readable reading 1e3 * "some data" x 2,465 ops/sec ±0.71% (87 runs sampled)
streams.web.Readable reading 1e3 * "some data" x 471 ops/sec ±0.39% (86 runs sampled)
Fastest is streams.Readable reading 1e3 * "some data"
```

**Comment by jasnell** [comment]
The results are not surprising. When running just a single iteration of the web streams vs node.js streams side-by-side, the performance comparison between the two should be nearly identical. However, when running it over-and-over, the web streams will be *much* slower for a number of reasons -- but mostly because of the heavy reliance on promises and the additional object allocations it requires. There are likely a number of performance optimizations that could be made internally but the web streams API was not designed for performance as much as it was designed for portability.

**Comment by RafaelGSS** [comment]
I see. Actually, I came across this benchmark because I'm investigating the `undici.fetch` performance (https://github.com/nodejs/undici/issues/1203), and following my analysis, one of the _slowest_ paths are in the `pullAlgorithm` that makes use of `WebStreams` (Readable/Writable).

The benchmarks in `undici` are also running it over-and-over, so the results make sense to this benchmark.

Thank you!

**Comment by RafaelGSS** [comment]
I see. Actually, I came across this benchmark because I'm investigating the `undici.fetch` performance (https://github.com/nodejs/undici/issues/1203), and following my analysis, one of the _slowest_ paths are in the `pullAlgorithm` that makes use of `WebStreams` (Readable/Writable).

The benchmarks in `undici` are also running it over-and-over, so the results make sense to this benchmark.

Thank you!

**Pull request merged**
